In [34]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler

In [35]:
volunteer = pd.read_csv('/content/leaf_dataset.csv')
volunteer.head(6)

,Class(species),specimen number,Eccentricity,Aspect Ratio,Elongation,Solidity,Stochastic Convexity,Isoperimetric Factor,Maximal Indentation Depth,Lobedness,Average Intensity,Average Contrast,Smoothness,Third moment,Uniformity,Entropy
0,1,1,0.72694,1.4742,0.32396,0.98535,1.00000,0.83592,0.004657,0.003947,0.047790,0.127950,0.016108,0.005232,0.000275,1.17560
1,1,2,0.74173,1.5257,0.36116,0.98152,0.99825,0.79867,0.005242,0.005002,0.024160,0.090476,0.008119,0.002708,0.000075,0.69659
2,1,3,0.76722,1.5725,0.38998,0.97755,1.00000,0.80812,0.007457,0.010121,0.011897,0.057445,0.003289,0.000921,0.000038,0.44348
3,1,4,0.73797,1.4597,0.35376,0.97566,1.00000,0.81697,0.006877,0.008607,0.015950,0.065491,0.004271,0.001154,0.000066,0.58785
4,1,5,0.82301,1.7707,0.44462,0.97698,1.00000,0.75493,0.007428,0.010042,0.007938,0.045339,0.002051,0.000560,0.000023,0.34214
5,1,6,0.72997,1.4892,0.34284,0.98755,1.00000,0.84482,0.004945,0.004451,0.010487,0.058528,0.003414,0.001125,0.000025,0.34068

In [36]:
type(volunteer)

pandas.core.frame.DataFrame

In [37]:
volunteer.isnull().sum()

volunteer[['Elongation', 'Maximal Indentation Depth', 'Lobedness', 'Average Contrast', 'Entropy']]

,Elongation,Maximal Indentation Depth,Lobedness,Average Contrast,Entropy
0,0.32396,0.004657,0.003947,0.127950,1.17560
1,0.36116,0.005242,0.005002,0.090476,0.69659
2,0.38998,0.007457,0.010121,0.057445,0.44348
3,0.35376,0.006877,0.008607,0.065491,0.58785
4,0.44462,0.007428,0.010042,0.045339,0.34214
...,...,...,...,...,...
335,0.81725,0.091860,1.535800,0.208610,2.02810
336,0.75319,0.078996,1.135800,0.218300,2.40590
337,0.78147,0.089763,1.466400,0.207030,1.69350
338,0.71532,0.113370,2.339400,0.135850,1.15260
339,0.85409,0.132270,3.184000,0.187820,1.56230

In [38]:
impute = SimpleImputer(missing_values = np.nan, strategy = 'mean')

impute.fit(volunteer[['Elongation']])
volunteer['Elongation'] = impute.transform(volunteer[['Elongation']])


impute.fit(volunteer[['Maximal Indentation Depth']])
volunteer['Maximal Indentation Depth'] = impute.transform(volunteer[['Maximal Indentation Depth']])


impute.fit(volunteer[['Lobedness']])
volunteer['Lobedness'] = impute.transform(volunteer[['Lobedness']])


impute.fit(volunteer[['Average Contrast']])
volunteer['Average Contrast'] = impute.transform(volunteer[['Average Contrast']])

impute.fit(volunteer[['Entropy']])
volunteer['Entropy'] = impute.transform(volunteer[['Entropy']])


volunteer.isnull().sum()

Class(species)               0
specimen number              0
Eccentricity                 0
Aspect Ratio                 0
Elongation                   0
Solidity                     0
Stochastic Convexity         0
Isoperimetric Factor         0
Maximal Indentation Depth    0
Lobedness                    0
Average Intensity            0
Average Contrast             0
Smoothness                   0
Third moment                 0
Uniformity                   0
Entropy                      0
dtype: int64

In [39]:
x = volunteer.iloc[:,2:]
x

y = volunteer.iloc[:,0:2]
y

y1 = volunteer[['Class(species)']]
y1

     Class(species)
0                 1
1                 1
2                 1
3                 1
4                 1
..              ...
335              36
336              36
337              36
338              36
339              36

[340 rows x 1 columns]

In [40]:
scaler = MinMaxScaler()

scaler.fit(x)

X_scaled = scaler.transform(x)

X_scaled

array([[0.69174143, 0.02593254, 0.25733589, ..., 0.16926451, 0.09145134,
        0.39628215],
       [0.70851718, 0.02878867, 0.30158315, ..., 0.08385882, 0.02317609,
        0.20762869],
       [0.73742953, 0.03138414, 0.33586288, ..., 0.02338769, 0.01057742,
        0.10794376],
       ...,
       [0.26809433, 0.00145857, 0.80151773, ..., 0.53773407, 0.15226298,
        0.60025206],
       [0.54762202, 0.00754794, 0.72283611, ..., 0.20166677, 0.08795854,
        0.38722382],
       [0.40251579, 0.00463081, 0.88789504, ..., 0.44854919, 0.10981331,
        0.54858021]])